### ISSUE TITLE
Setup API management for Access Management

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#120]
### Description

We need to setup API management for Access Management component

### Tasks
-  [x] Create Swagger files
-  [x] Import DEV
-  [x] Export dev
-  [x] Import AT21-AT24

### Acceptance Criteria
- [ ] API management is configured for AT
