### ISSUE TITLE
Get all the resources delegated to the current reportee by others (Inbound api delegations)

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management#122]
### Description

Get all the  resources (api) delegated by others to the reportee. The new userinterface [here](https://www.figma.com/proto/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=4352%3A114741&scaling=min-zoom&page-id=1209%3A8163&starting-point-node-id=4352%3A114741) requires that the api returns the following details to the frontend

- Name of the organisation that delegated the resource  to the reportee
-  resource(api) title list that each organisation delegated to the reportee 

### Tasks

- [x] Create an endpoint to list all the organisations that delegated the resources to the reportee
- [x] Add integration with sblbridge to get the party information
- [x] Test with different input
- [x] Create unit tests for the new endpoint

### Acceptance Criterias

The endpoint must return a list of organisation that delegated the resources  and each organisation lists the resources list.

**Comment by acn-dgopa** [comment]
Available for test after deploy to the test environment
