### ISSUE TITLE
Prepare App Frontend for Altinn Access Management

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#142]
### Description

This is an epic that list the different issues that need to be completed for the App Frontend

### In scope

- [ ] Setup React app
- [ ] Set up build pipeline 
- [ ] Set up publish pipeline for front end. (assumption it will be copied and hosted in the backend. See receipt component)
- [ ] Set up authentication (refresh functionality, and include cookies)
- [ ] Set up XSRF protection
- [ ] Implement components in design system
- [ ] Implement functionality

### Additional Information

We need to consider the following

- What kind of common functionality should be available (reporteelist, change language +++)

**Comment by sivaglen** [comment]
Lukker denne - åpnes hvis den blir relevant igjen. 

Ang "XSRF protection" følges opp i utviklingen av BFF.  @acn-dgopa sjekk at vi har kontroll. 

"Set up publish pipeline for front end" - @Albertlarsen har en issue på denn.
