### ISSUE TITLE
Create S2a-accordion + cypress component tests

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management#143]
Use DS-accordion to create an accordion where you can "Delete all", "Delete" and "Undo" a deletion. Important to make a line go over the deleted items. Use list with style dashed in AccordionContent. Remember to align the list items so they are right below the text in the accordion. 

![image](https://user-images.githubusercontent.com/31471142/195607717-d3f4a954-366f-4fc9-a6ff-9e234c8cacc4.png)

### Tasks

- [x] Set up Accordion with list
- [x] "Delete all/Slett alle", deletes all list items in AccordionContent
- [x] "Delete/Slett", deletes the chosen list item in AccordionContent
- [x] Deleted items gets line through them and is able to be "Undone/Angret"
- [x] "Undo/Angre", undoes the deletion of the list item
- [x] "Save/Lagre" removes the chosen entries from the list/accordion
- [x] "Delete all/Slett alle" opens the accordion to display all the items that will be deleted
- [x] Initial styling styling
- [x] Code cleanup
- [ ] Write Cypress tests

## Acceptance criterias:

- [ ] "Delete all/Slett alle", deletes all list items in AccordionContent
- [ ] "Delete/Slett", deletes the chosen list item in AccordionContent
- [ ] Deleted items gets line through them and is able to be "Undone/Angret"
- [ ] "Undo/Angre", undos the deletion of the list item
