### ISSUE TITLE
Create Policy Information Endpoint for PDP

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#146]
### Description

Access Management needs to expose an API to allow PDP to get all delegation changes for a given user, reportee and app/resource context.

Implementation of the actual lookup of DelegationChanges is already implemented in PolicyInformationPoint.FindAllDelegations.

### Tasks
- [ ] New PIP Controller and GET pip/delegations endpoint (with [ApiExplorerSettings(IgnoreApi = false)] as it's not to be exposed through APIM)
- [ ] New external model of DelegationChange and mapping

_No response_

### Acceptance Criterias

- [ ] Delegated policies for apps should be exposed
- [ ] Delegated policies for resources  should be exposed
- [ ] Needs to support indirect delegation through key roles or sub units

**Comment by jonkjetiloye** [comment]
@sivaglen @TheTechArch Tror denne feilaktig er satt til test, da det er ikke implementert noe API i accessmanagement for dette enda. Authorization har bare i dag en direkte integrasjon til postgres & blobstorage for app-delegeringer.

Det er ikke viktig for API delegering da PDP'en ikke brukes for autorisering for API-delegeringer.
Men denne endringen er noe som må på plass for migrering av enkeltdelegering og lenketjenester til A3.
