### ISSUE TITLE
Implement caching for service resources in access management

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management#147]
### Description

Resources (app,api,etc) are saved in resourceregistry table. The data is read and written to resource registry only through  resource registry component. The access management has a resource id tagged to each delegation. Current requirement for the app front end (for access management) requires that access management returns the name/description of the resource in relation to each delegation. To achieve this, access management has to retreive specified resource details for each delegation. This can be expensive call. To improve this, we need to cache the resources in access management component or in a global cache store.

### Tasks

- [ ] Analyze shared caching technique for caching resources
- [ ] Decide when to update the cache
- [ ] Implement caching

### Acceptance Criterias

- [ ] Cache is implemented for resources

**Comment by lovoll** [comment]
GetResource (id) and GetResouces (scope/ReourceType) has already caching in memory implemented by Jon Kjetil getRecorces cache all and filter afterwards so the filtering has to be done each request.
