### ISSUE TITLE
Expose Userprofile endpoint in Access-Management backend

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#156]
### Description

To support language, we need to get profile information to the frontend.

This is done through exposing a profile endpoint in Access Management backend

### Tasks

- [ ] Expose userprofile controller with userprofile information. Look at [Profile controller in App](https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Api/Controllers/ProfileController.cs)

### Acceptance Criteria

- [ ] Userprofile is exosed
- [ ] Only own userprofile is available
- [ ] Uses Userprofile component as source

**Comment by annerisbakk** [comment]
@Sondre-B denne er overtatt av @ekorra

**Comment by jonkjetiloye** [comment]
Implementation has since been moved to [altinn-access-manage](https://github.com/Altinn/altinn-access-management-frontend) and been tested and verified in both AT and TT environments
