### ISSUE TITLE
Move services from API project to Core and namespace cleanup

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#167]
### Description

Service interfaces and implementations should live in the Core project. Currently some have been added to the API project and needs to be moved.

There is still some namespace inconsistencies especially in the Core project which need cleanup.
There is a typo in Persistance -> Persistence

DelegationChangeEventQueue "service" implementation should be moved from Core to Persistence.
As should the implementation specific Configuration settings for PostgreSQL and AzureStoreage

### Tasks

- [x] Move services to Core project
- [x] Refactoring for typo in project and namespace Persistance -> Persistence
- [x] Move persistence specific implementations and Configuration from Core to Persistence project
- [x] Remove `Altinn.AccessManagement.Core.Services.Implementations` as folder and namespace
- [x] Sync namespaces for `Altinn.AccessManagement.Core.Services.Interfaces`
- [x] Sync namespaces for `Altinn.AccessManagement.Core.Clients.Interfaces`
- [x] Sync namespaces for `Altinn.AccessManagement.Core.Repositories.Interfaces`
