### ISSUE TITLE
Add support for configuring policy for a specific resource on API

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#174]
### Description

In policy enforcement point we support scenarios for accessing endpoints related to Apps.

We need to add support for RessourceAccessHandler

https://github.com/Altinn/altinn-studio/tree/master/src/Altinn.Common/Altinn.Common.PEP/Altinn.Common.PEP/Authorization

### Additional Information

How to handle sub resources?

### Tasks

- [x] Create ResourceAccessHandler 
- [x] Create ResourceAccessRequirement that support defining both action and resourceid
- [x] Create unit tests

### Acceptance Criterias

- [ ] Possible to configure API with resource access policy
- [ ] Authorize based on who parameter or possible other parameter
