### ISSUE TITLE
API for listing maskinporten supplier delegations for maskinporten and api owners

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#175]
### Description

We need an API that allows Maskinporten and API owners to check delegation between consumer and supplier organizations for a given scope.

Input will be 

- Consumerorg
- Supplierorg
- Scope

### Additional Information

Access to this API is controlled through API scopes ( #187) 

Altinn. Authorization.MaskinportenScopes [TODO Need to verify name]
Altinn.Authorization.MaskinportenScopesAdmin [TODO need to verify name]

Consumers with standard scope only get the list of delegations for resources they own themself in resource registry

Consumers with admin scope can ask for delegations for any resource. 

### Tasks

- [x] Create a new endpoint
- [x] Implement logic to search based on scopes.  We need to verify that we have the search capabilities needed in the resource registry
- [x] Implement filtering of results based on the scope
- [x] Unit tests

### Acceptance Criteria
As Maskinporten calling the existing Altinn2 Maskinporten-API (/maskinporten-api/delegations) when the API in proxy mode, I should:
- Receive the same HTTP status, message and body responses as before, for successful lookups when delegations exist
- Receive the same HTTP status, message and body responses as before, for successful lookups when no delegations exist
- Receive the same HTTP status, message and body responses as before, for errors/failure situations
- Token Authorization Scope; "altinn:maskinporten/delegations", should only give access to lookup delegations for the service owners own resources
- Token Authorization Scope; "altinn:maskinporten/delegations.admin", should give access to lookup delegations for any maskinporten scope delegation
- Without a valid token with authorized scope should give same error as in A2
