### ISSUE TITLE
Create API for listing resources for delegations

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#177]
### Description

We need an API for listing resources that can be delegated for a given reportee.

This will work as a proxy for the resource registry and will enforce filtering and

### Additional Information

This API should have the same search capabilities as the underlying resource registry API

 It should not filter based on the rights

### Tasks

- [x] Create resource API in Access management

### Acceptance Criteria

- [ ] You can search for the same type of criteria like resource registry search API allows
- [ ] Resources that has enabled SRR/RRR need to be filtered based on reportee
- [ ] Return simpliefied resource. (name, description, owner, delegation description, refenren++, )
- [ ] Use custom path for this type of resource (discuss path)

**Comment by jonkjetiloye** [comment]
This has since been removed from access-management, and now is the responsibility of the BFF/AM-UI and tested through frontend cypress tests. Closing issue
