### ISSUE TITLE
Support resource information in access management

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#185]
### Description

We need information about resources when doing database queries in Access management for delegations. (and possibly other scenarios in the future)

Resource Registry need to publish information to AccessManagement when new resources is created or resources is updated

### Additional Information

Do we need to support 
- Change of resource?  (Assumption, not after production)
- Change of resource type (Assumption, not after in-production)

### Tasks

- [ ] Add Table for AuthorizationResources in AccessManagement schema
- [ ] Add API for creating AutorizationResources
- [ ] Add API for updating AuthorizationResourcen
- [ ] Define the Internal model for AuthorizationResource
- [ ] Define the external model for an authorization resource

**Comment by jonkjetiloye** [comment]
Tested and verified as part of delegation scheme migration test run in TT02. Closing issue
