### ISSUE TITLE
Rewrite partiesclient such that it retreives party information via internal register api  

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management#186]
### Description

Delegations Api has the need to return offeredby, coveredby names for a delegation. Therefore, it retreives the party information via partyclient. The partyclient retreives the information via SBL bridge. This has to be modified to use the register api.

Also, implementation in SBL bridge for retreiving a list of party information must also be moved to Register Api.

### Tasks

- [x] Implement GetParties in Register Api (Which team is responsible for this implementation?)
- [x] Remove the use of sbl bridge
- [x] implement reference to internal register api

**Comment by sivaglen** [comment]
@acn-dgopa er dette noe vi må gjøre for å produksjonssette Delegerbare API ressurser?

**Comment by acn-dgopa** [comment]
@sivaglen ja. Det er nå gjørt og tilgjengelig for testing

**Comment by jonkjetiloye** [comment]
Technical implementation change which has been tested and verified. Closing issue
