### ISSUE TITLE
Api for syncing Resource information

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#198]
### Description

We need to expose an api in access management so Resource Registry can update the central metadata information in access management database

### Tasks

- [x] Expose API with minal Resource model
- [x] Integrate with db to update the resource metadata table in access management
- [x] Update resource registry to call this API when creating and updating resource

### Acceptance Criterias

- [x] Possible for Resource Registry to call to create and update resource info in access management
- [x] When resource registry changes or created resource, this is synced with access management

**Comment by jonkjetiloye** [comment]
Verified through test migration run in both AT and TT environments. Closing issue
