### ISSUE TITLE
Configure resource authorization on end user API for maskinporten delegation

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#219]
### Description

With the support for resource configuration in PEP it is now possible to configure resource policy for API endpoints

### Tasks

- [ ] Identify end user API for maskinporten delegations
- [ ] Configure policy for relevant endpoints
- [ ] Set up local test for handling it

**Comment by jonkjetiloye** [comment]
Tested and verified through both API and am-ui in AT
