### ISSUE TITLE
Api for reportee lookup

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#224]
### Description

We need an API that based on party id returns information if it is a valid reporter for the user

### Tasks

- [ ] Expose party AP for returning party information for a given party ID

### Acceptance Criterias

- [ ] Only return party information for valid reportees
- [ ] Clean SSN. (implement util when mapping to external entity)

**Comment by jonkjetiloye** [comment]
Reportee lookup API er ikke lenger i bruk Har laget #781 for å rydde det bort igjen.
