### ISSUE TITLE
Create API delegation status API

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#249]
### Description

We need an API to check if and what rights a user can delegate for a specific resource, app or altinn 2 service.

### Additional Information

- API will require user authentication token
- Input will be reportee and resourceId, org/app or service codes
- The output would be a new simple object with a response type that both external services and our own BFF/front-end can use
to display all available rights and select rights from in order to perform a single-right delegation for the service/app/resource.
- All irrelevant rules for delegation (serviceowner org subject etc.) are to be discarded and not a part of the response model.

Each individual right must specify the status/result whether:
1. Recipient already has the right
2. Authenticated user can delegate the right
3. Authenticated user cannot delegate the right
3.1 When possible: Why not (FaultCode and Reason)

Suggested API endpoint design:
https://app.swaggerhub.com/apis/jonkjetiloye/Accessmanagement/1.0.0#/Rights%20delegation/PostRightsDelegationUserDelegationCheck

Service implementation for app and resource rights can be based on the current implementation of PolicyInformationPoint.GetRights w/getDelegableRights=true

Remaining functional clarifications:
- [x] Security level requirement for new AccessManagement system resource. Answer: 3
- [x] Should resource/service security level requirement should limit delegation? Answer: No
- [x] Should API for ResourceId also support MaskinportenSchema and SystemResources? Answer: Yes/No (implementation will be agnostic. The ServiceResource model will declare whether the resource is delegable or not. But will need a separate endpoint (MaskinportenSchema/DelegationCheck) for MaskinportenSchema since authorization for the endpoints will differ)

### Tasks

- [x] Create Controller endpoints
- [ ] Create SBL Client implementation for SBL Bridge endpoint for A2 service
- [ ] Create mapping from SBL Bridge non-200 responses to Validation/ProblemDetails model used in A3
- [ ] Update Details response model [for changes](https://app.swaggerhub.com/apis/jonkjetiloye/Accessmanagement/1.0.0#/Rights%20delegation/PostRightsDelegationUserDelegationCheck) and sync detail and parameter codes with [A2 implementation](https://dev.azure.com/digdir/Altinn/_git/Altinn/pullrequest/6452)
- [x] Service implementation for RightsHelper.GetRightsQuery expanded to support Altinn Apps
- [x] Create unit/integration tests
- [ ] Create K6 tests

### Acceptance Criteria
- [ ] API requires authenticated user to have Read on new AccessManagement system resource (which is provided to HADM and ADMAI roles) for the reportee party 
- [ ] If no rights can be delegated, all available rights of the resource/service should be returned with "NotDelegable" status
- [ ] For each right a Details model should be returned with a Code, Description and Parameters describing the status (why/why not the right is delegable)

#### K6 testdata requirements and delegation scenarios:
Testdata requirements:

Will need Resourceregistry resource(s) (incl. MaskinportenSchema?) + Altinn 3 App(s) + Altinn 2 Service(s) which support the following main delegation access scenarios:

1. DAGL/HADM delegable (without having the actual resource access themselves)
2. ADMAI + Role access to the delegation resource
3. ADMAI + Single right access to the delegation resource
4. ADMAI + Non-delegable resource/app/service
