### ISSUE TITLE
Test deployment and integration of frontend-backend

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#256]
### Description

We need to start testing the integration of the frontend and backend.  We will setup a automatic job that can build and copy files from frontend to backend repo. But before this is ready we can test with a manual deploy and copy of files to altinn-access-management repo

### Tasks

1. Build frontend and add dist files to wwwroot in AccessManagement backend. This includes javascript files 
2. Update config/razor view to point to correct files
3. Deploy container with frontend
4. Logint to AT22 and verify that javascript runs 
5. 

### Acceptance Criterias
- [x] Access Management frontend runs as expected
- [x] Have access to needed files like language and other dist files
- [x] No error messages
- [x] IDentified issues are created in github
