### ISSUE TITLE
UX-specification of components

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management#26]
### Description

We in team authorization needs UX specification on several components that are going to be created in the design system before we're able to develop them. This is a top to bottom priority list where the item on top of the list has the highest priority. The issues that need ux specification can be found following the link to the issue.

### Tasks

- [x] IconButton - https://github.com/Altinn/altinn-design-system/issues/79
- [x] Button variant action - https://github.com/Altinn/altinn-design-system/issues/26
- [x] List Item Button - https://github.com/Altinn/altinn-design-system/issues/98
- [x] Merge API-delegering view S1 and S2.
- [x] Decide new background color for API-delegering views S2, S3, S4 and S5
- [x] Design API-delegering for smaller screens below 768 px.

-------------------------- Less Priority-------------------------------------------------
- [x] Link button - https://github.com/Altinn/altinn-design-system/issues/96
- [x] Klientdelegering - This whole Accordion and flow described in the issue needs a breakdown https://github.com/Altinn/altinn-authorization-admin/issues/23
- [x] Page - https://github.com/Altinn/altinn-design-system/issues/57
