### ISSUE TITLE
Redirect to  access management url to the same domain after login

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management#270]
### Description

Go to https://platform.at22.altinn.cloud/accessmanagement/
When the user is not logged in, the user is redirected to login methods. When the user is logged in, user is redirected to https://internal.platform.at22.altinn.cloud/accessmanagement. 
The user has to be instead redirected to https://platform.at22.altinn.cloud/accessmanagement/

### Tasks

- [x] Find out why the host is set to internal.platoform.altinn.cloud. Fix the code to redirect to right domain
- [x] Goto url is hardcoded. Instead get the requested path

### Acceptance Criterias
- [ ] When user is logged in, redirect to https://platform.at22.altinn.cloud/accessmanagement/ (or a different home page)

**Comment by acn-dgopa** [comment]
#256
