### ISSUE TITLE
Parameterize CDN links to be used in home conroller and clean up frontend files

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management#275]
### Description

The entrypoint javascript/css must be served through a app setting configuration.

### Tasks

- [x]  Add a appsetting configuration for js/css url in cdn
- [x] clean the frontend resources from the repository as it will be served via cdn.
- [x] Update the appsetting to use local storage accounts

### Acceptance Criterias
- [ ] Settings updated in appsettings
- [ ] frontend assets are removed from wwwroot
- [ ] appsetting updated with local storage url
