### ISSUE TITLE
Backend for Frontend

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management#283]
### Description

We need a backend api for serving customised data to frontend requests.

### Tasks

- [x] Create a new .net project for bff api
- [x] add the inbound/outbound api endpoints to the bff project
- [x] add language support for resource information
- [x] add the resource registry client service
- [x] add profile client service

### Acceptance Criterias

- It should be possible to fetch inbound/outbound delegations by sending a party id
- It should be possible to fetch inbound/outbound delegations by sending party as "organization" and header "party-organizationumber"
- The inbound/outbound delegations msut be returned with resource information returned in user's preferred language
