### ISSUE TITLE
Setup Altinn Access Management BFF as Azure Container App

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#288]
### Description

To try out a new hosting strategy we will use Altinn Access Management BFF as pilot for [Azure Container Apps](https://azure.microsoft.com/en-us/products/container-apps/)

This is a new product in Azure that lets you host your application as a container without setting up AKS. 

 

### Access Token

BFF will need access to a private certificate to generate an access token for calling protected APIS.

In AKS this is made available through disk in AKS Cluster. 

With Azure Container Apps the assumption is that we need to get access to the KeyVault

### Access to key vault

We need to figure out how to access the key vault for aks container apps.  SAS key as environment secret is possibly an option

Are there any alternative to a keyvault for this?

### Security

We need to consider this document  https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/azure-container-apps-security-baseline

### Subscription strategy?

Should we have a separate subscription for authorization?`

### Application insights

How to configure application insights to get full stack tracing

### Network?

Should container apps have any network privileges compare to other apps on internet?

### Tasks

- [x] Configure container for BFF
- [x] Setup deploy pipeline
- [x] Update Access Token with support for Keyvault (client nuget)
- [x] Analyze the domain/dns setup for environments (am.altinn.no?)
- [x] Setup infrastructure script for container app.

**Comment by sivaglen** [comment]
@TheTechArch eller @jonkjetiloye - kan denne lukkes?

**Comment by jonkjetiloye** [comment]
@sivaglen @TheTechArch Tasks for setup av deploy pipeline og infrastruktur script er jo det som det fortsatt jobbes med.
Med mindre vi har dobbelt opp med noen issues her da.

**Comment by jonkjetiloye** [comment]
Lukker denne da oppsett og avklaringer for setup er gjort. Det eneste som gjenstår er resterende setup av infrastrukturen som  følges opp i egen isssue:
https://github.com/Altinn/altinn-access-management-frontend/issues/212
