### ISSUE TITLE
Setup scope authorization for Maskinporten delegations API used for proxy/maskinporten integration

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#299]
### Description

The Delegations API: accessmanagement/api/v1/admin/delegations/maskinportenschema
used by the A2 Maskinporten API proxy is currently not setup with an authorization policy to match the scope requirements of the API in A2 (altinn:maskinporten/delegations and altinn:maskinporten/delegations.admin)

### Tasks

- [ ] Setup policy in program.cs using ScopeAccessRequirement for the same scopes as required by A2 API (altinn:maskinporten/delegations and altinn:maskinporten/delegations.admin)
- [ ] Use the policy in the [Authorize(Policy = AuthzConstants.????)] controller operation attribute
- [ ] Implement custom authorization in service implementation (if not already done) so admin-scope gives access to lookup for all service owners, while non-admin scope only gives access to the authenticated service owners own resources.
- [ ] Implement use of OidcProviders configuration allowing for support of both ver2 and test MP-tokens

### Acceptance Criterias

As Maskinporten calling the existing Altinn2 Maskinporten-API (/maskinporten-api/delegations) when the API in proxy mode:

- Token Authorization Scope; "altinn:maskinporten/delegations", should only give access to lookup delegations for the service owners own resources
- Token Authorization Scope; "altinn:maskinporten/delegations.admin", should give access to lookup delegations for any maskinporten scope delegation
- Without a valid token with authorized scope should give same error as in A2
- Support for authentication using both ver2 and new test-issuer of Maskinporten-tokens
