### ISSUE TITLE
Setup deploy pipeline access management

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#3]
## Description

We need to set up a deployment pipeline for authorization admin

## Consideration

- Should the frontend and backend be deployed together? 

## Requirements
- Support all environments

## Task
- [x] Setup deploy files pipeline
- [x] Set up container build and push pipeline
- [x] Set up release pipelines
