### ISSUE TITLE
Accessmanagement: Sync appsettings and configuration with values.yaml for environment deploy values

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#311]
### Description

There is several missing and/or differently named appsettings/config values currently in comparison with the environment deploy values (see separate PR for updating values.yaml)

### Tasks

- [x] Remove uneccessary ResourceRegistrySettings file and add `ApiResourceRegistryEndpoint ` under `PlatformSettings`
- [x] Fix and sync naming of Api endpoints with values.yaml

### Acceptance Criterias

- [x] Stuff works when deployed to AT

**Comment by jonkjetiloye** [comment]
Tested in AT21-24 MaskinportenSchema delegation now correctly authorizes based on authenticated users access to system resource created in the resource registry
