### ISSUE TITLE
Remove API endpoint version from appsettings and deploy values and into client implementations

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#325]
### Description

As we go live with APIs in Access Management and Resource Registry and external solutions start to integrate with our APIs any need for versioning of individual endpoints will now not be possible since the version `/v1/` from the endpoint path is currently in the configured appsettings.json and values.yaml environment variables.

Instead the version should be controlled by the client implementations in code

### Tasks

- [ ] Remove `/v1/` from endpoint configuration values in appsettings.json and values.yaml
- [ ] Include api version in path for individual client implementations

### Acceptance Criterias

- [ ] Nothing breaks in deployed environments
- [ ] Possible to version a single endpoint in code alone

**Comment by sivaglen** [comment]
Må vurderes før vi publiserer API for ekstern bruk og har behov for versjonering. Lukker saken.
