### ISSUE TITLE
Proxy MaskinportenAPI for Delegations error response mapping

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#326]
### Description

Problem 1 (in Altinn 3):
Currently the new API for serviceowner/maskinporten integration for getting delegations only return basic httpstatus codes and reason phrase.

The API should return ProblemDetails response in the body same as the other MaskinportenSchema API endpoints have been implemented with.

Problem 2 (in Altinn 2):
The second problem is that error responses from the new API will need to be mapped in the Altinn 2 MaskinportenAPI in order to not be breaking with the existing http response codes, error codes and messages currently in use in the existing API.

Currently the A2 MaskinportenAPI uses a custom error response model:

```
{
  "error_code": 500,
  "error_description": "Altinn 3.0 Technical error: HTTP Unauthorized. Reason: Unauthorized. Request: https://platform.at22.altinn.cloud/accessmanagement/api/v1/admin/delegations/maskinportenschema?supplierOrg=910459880&consumerOrg=810418672&scope=altinn:resourceregistry:jks_audi_etron_gt.drive"
}
```
Which as the above example shows any errors given by the A3 API will now change the behaviour and return 500 Internal Server Error 

### Tasks

- [ ] All error responses must be changed to return as a ProblemDetails model

### Acceptance Criterias

As Maskinporten calling the existing Altinn2 Maskinporten-API (/maskinporten-api/delegations) when the API in proxy mode, I should:

- [ ] Receive the same HTTP status, message and body responses as before, for successful lookups when delegations exist
- [ ] Receive the same HTTP status, message and body responses as before, for successful lookups when no delegations exist
- [ ] Receive the same HTTP status, message and body responses as before, for errors/failure situations
- [ ] Token Authorization Scope; "altinn:maskinporten/delegations", should only give access to lookup delegations for the service owners own resources
- [ ] Token Authorization Scope; "altinn:maskinporten/delegations.admin", should give access to lookup delegations for any maskinporten scope delegation
- [ ] Without a valid token with authorized scope should give same error as in A2
