### ISSUE TITLE
Tilby autorisasjon for dialogporten

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management#346]
# Overordnet beskrivelse 
Dialogporten i Altinn 3 er en løsning hvor tjenesteeiere kan publisere dialoger i en felles brukerflate slik at sluttbruker og systemer kun trenger forholde seg til en flate mot de offentlige. 

Dette vil være en del av løsningen som legger til rette for å flytte meldingstjenester fra Altinn 2 til Altinn 3. 
Autorisasjonsløsningen i Altinn 3 skal legge til rette for autorisasjon i Dialogporten der man kan kan styre tilgang til det enkelte dialogelement.

# Overordnet beskrivelse av løsning

Det vil sannsynligvis være behov for følgende i [Dialogporten](https://digdir.github.io/dialogporten):  
•	Autorisasjon av elementer/dialoger i Dialogportens API og felles arbeidsflate 
•	Autorisasjon av eventer som opprettes og sendes av Dialogporten og tjenesteleverandørs løsninger
•	Autorisasjon av dialoger i den enkelte tjenesteleverandør API 

Det er antatt at denne Epicen og så vil løse [Klargjøre Autorisasjon Altinn 3 for migrering av meldingstjenester ](https://github.com/Altinn/altinn-access-management/issues/345)
 

# Forutsettninger
- Forutsetter at konseptet virksomhetsbruker er landet og løst 
- Autorisasjon av eventer løses i egen oppgave

```[tasklist]
### Identifiserte task
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/286. -> verification
- [ ] Verify the needed level of delegations and resources for a dialog -> verification
- [x] https://github.com/Altinn/altinn-access-management/issues/539 -> 24 Q1
- [x] PDP kan autorisere basert på policy for ressurs
- [x] https://github.com/Altinn/altinn-authorization/issues/676 -> 23 Q4
- [x] https://github.com/Altinn/altinn-access-management/issues/563 -> 24 Q1
- [x] https://github.com/Altinn/altinn-authorization/issues/578 -> 24 Q1
- [ ] #21 -> 25
- [x] https://github.com/Altinn/altinn-access-management/issues/540 -> 24 Q2
```

# Spørsmål

**Comment by annerisbakk** [comment]
@ekorra lukker denne. Avtalt med dialogporten at det som gjenstår på denne Epicen løses i andre Epics.
