### ISSUE TITLE
Flytte styring av enkelttilganger til Altinn 3

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management#362]
![image](https://github.com/Altinn/altinn-access-management/assets/22012997/327500d2-4a27-4f64-b3b8-2448ff91e072)

## Overordnet beskrivelse
Utvikle løsning for å kunne styre tilgang til enkeltrettigheter i Altinn 3 (A3). Støtten som pr i dag finnes i Altinn 2 (A2) skal da overføres til ny løsning i A3 med nytt design, ny frittstående frontend og nye backend API. APIene skal kunne brukes direkte av sluttbrukersystem eller gjennom vår egen frontend.

### Hva er en enkelttilgang?
En enkelttilgang gir en bruker tilgang til å utføre en enkelt handling (eks: les, skriv, aktiver) på en enkelt tjeneste (eks: trehuggeskjema, timeføringsapp, legeresept i et eksternt system). Ved å delegere en slik enkeltrettighet vil en bruker med andre ord gi noen andre (person/org/system) tilgang til å utføre denne handlingen på vegne av brukeren selv eller organisasjonen som brukeren representerer.

### Hvilke tjenester kan delegeres tilgang til?
Det er 3 typer tjenester som dekkes under delegering av enkelttilganger:
- A2-services: Dette inkluderer skjema i A2 og det som tildligere har blitt kalt lenketjenester (eks: trehuggeskjema)
- A3-apper: Dette er de nye 'skjemaene' i Altinn, men siden de er mere avanserte kalles de nå apper (eks: timeføringsapp)
- Resursser i ResursRegisteret(RR): Det blir laget et eget register for A3-tjenester som ikke er Apper. Dette kan være Altinn-hostede tjenester eller eksterne tjenester. (Eks: legeresept i et eksternt system)

A2-services som er migrert til A3 blir enten A3-apper eller Resurser i RR.

### Hva skal leveres: 
- Nytt GUI i A3 for delegering av enkeltrettilganger for A3-resurser (resurser i resursregisteret + A3 apper) og A2-tjenester
- Nytt GUI i A3 for å be om enkelttilganger for A3-resurser (resurser i resursregisteret + A3 apper) og A2-tjenester
- Nytt GUI i A3 for å godkjenne forespørsler om enkelttilganger
- Nødvendige endringer i GUI i A2 for å støtte at delegering av enkelttilganger er flyttet til A3
  - Det skal ikke utvikles nytt GUI for administrasjon av aktive enkeltdelegeringer (viwet i bildet). Her skal det eksisterende GUI i A2 bestå for nå. Det skal imidlertid benytte nye A3-endepunkt for visning og sletting av aktive delegeringer, samt sende bruker videre til nytt GUI i A3 for å gjøre nye delegeringer.
- Nye API som håndterer at resurser KAN være migrert fra A2 til A3 (ref API strategi)
  - inkl nye api for avgiverliste for sluttbrukersystem og tjeensteeier

## Analyse av leveransen

```[tasklist]
### Analyse
- [ ] https://github.com/Altinn/altinn-authorization/issues/242
```

## Features som inngår i denne leveransen

```[tasklist]
### Features
- [ ] Delegere enkelttilganger
- [ ] Slette enkelttilganger
- [ ] Vise aktive enkelttilganger
- [ ] Be om enkelttilganger
- [ ] Godkjenne forespørsel om enkelttilganger
- [ ] Avgiverliste: https://dev.azure.com/digdir/Altinn/_workitems/edit/63179
```

.
.
.
.
.
.
.
.
.

----

## Gammel tasklist

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-access-management-frontend/issues/114
- [ ] https://github.com/Altinn/altinn-access-management-frontend/issues/133
- [x] Avgiverliste: https://dev.azure.com/digdir/Altinn/_workitems/edit/63179
- [x] Gi og fjerne rettigheter https://dev.azure.com/digdir/Altinn/_boards/board/t/Team%20Commodore/Stories/?workitem=62937
- [ ] Mine skjema og rettigheter https://dev.azure.com/digdir/Altinn/_workitems/edit/63182
- [ ] https://github.com/Altinn/altinn-access-management/issues/146
- [ ] https://github.com/Altinn/altinn-authorization/issues/242
```
