### ISSUE TITLE
Flytte funksjonalitet for å be om tilgang (delegationrequest)

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management#363]
## Overordnet beskrivelse
DelegationRequest lar bruker som trenger tilgang til en tjeneste opprette en forespørsel som tilgangsstyrer senere kan godkjenne eller avvise.  
Denne funksjonaliteten utvikles på nytt i Altinn 3 og registrerte DelegationRequest vil flyttes over fra gammel til ny løsning. Det lages nye API og konsumenter må ta disse i bruk i forbindelse med at funksjonaliteten flyttes.   

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-access-management/issues/332
- [ ] https://github.com/Altinn/altinn-authorization/issues/20
- [ ] https://github.com/Altinn/altinn-access-management/issues/262
```

**Comment by annerisbakk** [comment]
Lukkes - følges opp av #692
