### ISSUE TITLE
Refactoring urn used for attribute id for resource registry ids

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#364]
### Description

In discussions and design for supporing authorization of events and the new integration for the new OED (oppgjør etter dødsfall), 
it's been concluded that the current `urn:altinn:resourceregistry` attribute should instead be `urn:altinn:resource`, as well as a future attribute id for instance sub-resources as `urn:altinn:resourceinstance`

### Tasks

- [x] Refactoring the XacmlRequestAttribute.ResourceRegistryAttribute
- [x] Refactoring the AltinnXacmlConstants.MatchAttributeIdentifiers.ResourceRegistryAttribute
- [x] Refactoring all test data and policies for integration tests
- [x] Existing delegations in AT-environments can be dropped
- [x] The policy for the API-SystemResource must also be updated

**Comment by jonkjetiloye** [comment]
Verified in AT23 after all repos/components have been updated for the new resource id
