### ISSUE TITLE
Rights delegation API endpoint

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#472]
### Description

Swagger hub API design of the endpoint: https://app.swaggerhub.com/apis/jonkjetiloye/Accessmanagement/1.0.0#/Rights%20delegation/PostRightDelegationOffered

We need a new Rights API for POST requests for creating/performing a delegation of rights on behalf of a reportee.

Rights can be for a given resource from the resource-registry, an A3 Altinn app or A2 service.
Delegation can either be for a single right, or all available rights a user can delegate for a given resource/app/service.

Which rights are available for a given user to delegate on behalf of the reportee can be retrieved from the [User Delegation Check API](https://github.com/Altinn/altinn-access-management/issues/249)

### Tasks

- [ ] New POST endpoint in the Rights controller requiring ADMAI/Tilgangsstyrer system resource for the reportee {party}
- [ ] New AttributeId: 'urn:altinn:lastname'(??) needed as delegation to SSN will also need verification of LastName of the user (need rate-limiting / Retry-After response for failed attempts?)
- [ ] Delegation service implementation which based on the request identifies the type of resource (resource-registry / app / a2 service) and performes the delegation accordingly
- [ ] Bridge client implementation for A2 delegation
- [ ] Resource/App delegation must implement it's own validation logic (similar to MaskinportenSchemaService.ValidateMaskinportenDelegationModel)

### Acceptance Criterias

As a main administrator/tilgangsstyrer or user with Write access for the altinn_access_management resource (w/ security level 3 requirement), for a reportee/myself
I should be authorized to delegate rights for a resource from the resource-registry/an A3 Altinn app/A2 service
If I have the neccessary rights to delegate the rights, as defined by the XACML policy of the resource

- [ ] Self delegation should only be possible by users if they are Main Administrator (HADM) for the reportee
- [ ] Self delegation should not be possible for organizations (from and to the same organization/party) regardless of who the autenticated user is
- [ ] Delegation to SSN must be accompanied by LastName attribute and verified, or rate-limited / Retry-After response for multiple failed attempts
- [ ] In a single POST request it should only be possible to delegate rights for the same App/Resource/Altinn 2 Service. 
- [ ] Must support delegation To a Enterprise User

**Comment by acn-Sneha** [comment]
@jonkjetiloye @ivartryti har du mulighet å sjekke at de testene har vi i bruno? Jeg ser det ikke, men bra hvis @ivartryti kunne ta en titt på den?

**Comment by acn-Sneha** [comment]
@jonkjetiloye Mangler vi automatisk negative tester i denne tasken?
