### ISSUE TITLE
Test Design: Scenarios for Single rights delegations

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#493]
### Tasks:

- [x] Identify the scenarios
- [x] Identify test data which can be used for the scenarios
- [x] Come up with detailed scenarios
- [x] Priorities test scenarios according the priority
- [x] Identify test scenarios which needs to be automated in cypress/ Bruno and which needs to be run manually

### Testdata Requirements:

Will need:
- Resourceregistry resource(s) (incl. MaskinportenSchema)
  K6 resurces should perhaps not be visible?
- Altinn 3 App(s) 
- Altinn 2 Service(s) (incl. SRR) (Access-operasjonstjeneste)

which support the following main delegation access scenarios:

1. DAGL/HADM delegable (without having the actual resource access themselves)
2. ADMAI + Role access to the delegation resource
	2.1 Direct role delegation to user (incl. ER-roles)
	2.2 Direct role delegation from Main Unit to user 
	2.3 Role delegation to users key role unit
	2.4 Role delegation from Main Unit to users key role unit
3. ADMAI + Single right access to the delegation resource
	3.1 Direct resource delegation to user (incl. ER-roles)
	3.2 Direct resource delegation from Main Unit to user 
	3.3 Resource delegation to users key role unit
	3.4 Resource delegation from Main Unit to users key role unit
4. HADM/ADMAI + Non-delegable resource/app/service (Negative tests)
5. User (without HADM/ADMAI) + Delegable resource (Negative tests)

Organizations:
- A main unit with at least one subunit (BEDR/AAFY) incl. DAGL user
- ENK with an Enk-owner (INNH) incl. REVI/REGN org for ENK incl. DAGL user and employee having received client delegation + ADMAI on behalf of ENK
- A "normal" organization incl. DAGL user and 2x ADMAI users

Persons:
- Any of the above users tied to organizations can be reused for delegations on behalf of self
- 2 x ADMAI users for another person needed (delegation access scenario 2 & 3)

Users:
- Enterprise user for an organization (any of the above organizations can be reused) incl. DAGL

### Test Scenario Notation

notation example 1: `2-A-OtP`
notation explanation: Delegation access scenario 2 (ADMAI + Role access), delegation of an Altinn App, from Organization to a Person

notation example 2: `1-R(MS)-OtO`
notation explanation: Delegation access scenario 1 (HADM), delegation of a Resource of type MaskinportenSchema, from an Organization to an Organization

notation example 3: `5-S-PtE-Neg`
notation explanation: Delegation access scenarion 5 User (without HADM/ADMAI), delegation of an Altinn 2 Service, from a Person to an Enterpriseuser, negative test (should not succeed)

### Delegation scenarios on behalf of an Organization:

1-R-OtP
1-A-OtP
1-S-OtP
1-S(SRR)-OtP
1-S(SRR)-OtP-Neg
1-R(MS)-OtP-Neg

1-R-OtO
1-A-OtO
1-S-OtO
1-R(MS)-OtO

1-R-OtE
1-A-OtE
1-S-OtE
1-R(MS)-OtE-Neg

2-R-OtP
2-A-OtP
2-S-OtP
2-R(MS)-OtP-Neg

2-R-OtO
2-A-OtO
2-S-OtO
2-R(MS)-OtO

2-R-OtE
2-A-OtE
2-S-OtE
2-R(MS)-OtE-Neg

3-R-OtP
3-A-OtP
3-S-OtP
3-R(MS)-OtP-Neg

3-R-OtO
3-A-OtO
3-S-OtO
3-R(MS)-OtO

3-R-OtE
3-A-OtE
3-S-OtE
3-R(MS)-OtE-Neg

4-R-OtP-Neg
4-A-OtP-Neg
4-S-OtP-Neg

4-R-OtO-Neg
4-A-OtO-Neg
4-S-OtO-Neg
4-R(MS)-OtO-Neg

4-R-OtE-Neg
4-A-OtE-Neg
4-S-OtE-Neg

5-R-OtP-Neg
5-A-OtP-Neg
5-S-OtP-Neg

5-R-OtO-Neg
5-A-OtO-Neg
5-S-OtO-Neg
5-R(MS)-OtO-Neg

5-R-OtE-Neg
5-A-OtE-Neg
5-S-OtE-Neg

### Delegation scenarios on behalf of an Person:

2-R-PtP
2-A-PtP
2-S-PtP

2-R-PtO
2-A-PtO
2-S-PtO
2-R(MS)-PtO-Neg

2-R-PtE-Neg
2-A-PtE-Neg
2-S-PtE-Neg

3-R-PtP
3-A-PtP
3-S-PtP

3-R-PtO
3-A-PtO
3-S-PtO
3-R(MS)-PtO-Neg

3-R-PtE-Neg
3-A-PtE-Neg
3-S-PtE-Neg

4-R-PtP-Neg
4-A-PtP-Neg
4-S-PtP-Neg

4-R-PtO-Neg
4-A-PtO-Neg
4-S-PtO-Neg
4-R(MS)-PtO-Neg

4-R-PtE-Neg
4-A-PtE-Neg
4-S-PtE-Neg

5-R-PtP-Neg
5-A-PtP-Neg
5-S-PtP-Neg

5-R-PtO-Neg
5-A-PtO-Neg
5-S-PtO-Neg
5-R(MS)-PtO-Neg

5-R-PtE-Neg
5-A-PtE-Neg
5-S-PtE-Neg

**Comment by anishastphen** [comment]
@acn-Sneha can u upload the test scenarios sheet here so that is accessible for everyone?

**Comment by acn-Sneha** [comment]
@anishastphen Have attached file 

[detailed scenarios_enkeltrettigheter.xlsx](https://github.com/Altinn/altinn-access-management/files/14023010/detailed.scenarios_enkeltrettigheter.xlsx)

**Comment by acn-Sneha** [comment]
@jonkjetiloye @rtafj Lukker tasken siden vi har verifisert det og skal utvikle noen av scenarios under playwright :)
