### ISSUE TITLE
Rights Offered API endpoint (GET /{party}/rights/delegation/offered)

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#498]
### Description

Swagger hub API design of the endpoint: https://app.swaggerhub.com/apis/jonkjetiloye/Accessmanagement/1.0.0#/Rights%20delegation/GetRightDelegationOffered

We need a new Rights API endpoint for GET requests for retrieving all offered single rights delegations on behalf of a given reportee.

All offered single rights performed in the [POST endpoint](https://github.com/Altinn/altinn-access-management/issues/472) for resources from the resource-registry or A3 Altinn apps should be returned by this new endpoint. 

### Additional Information

Being clarified:
- [ ] Should SSN for persons be sensored or not?

### Tasks

- [ ] New GET endpoint in the Rights controller requiring Read for the 'altinn_access_management' system resource for the reportee {party}
- [ ] Right service implementation which based on the reportee {party} looks up both all delegated resources and delegated apps

### Acceptance Criterias

As a main administrator/tilgangsstyrer or user with Read access for the altinn_access_management resource (w/ security level 3 requirement), for a reportee/myself
I should be authorized to revoke offered rights the reportee/myself have made to others
for all resource-registry resources or altinn 3 app the reportee/myself have delegated to others
including details about the action/rights and the recipient org/person/user

### Dependencies
-  blocked by this #472

**Comment by ivartryti** [comment]
Made a WIP branch: https://github.com/Altinn/altinn-access-management/tree/feature/498-rights-offered-api-endpoint
