### ISSUE TITLE
Kartlegging av Team formidling sine behov for autorisasjon på ny løsning

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-access-management#499]
Møte med team formidling for å høre planer og behov som de har for autorisasjon av formidlingstjeneste på ny løsning.
```[tasklist]
### Tasks
- [ ] RRR - Q1
- [ ] Ressursregister - Q1
- [ ] Systembruker - Q2
- [ ] Delegering av enkeltrettigheter - Q2
- [ ] Delegering av rettighetspakker - Qx
- [ ] Ny ressurstype i ressursregisteret - Q1
- [ ] Ekstern PDP
```
