### ISSUE TITLE
Update access-management for changes in resource-registry models

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#500]
### Description

Ref.: https://github.com/Altinn/altinn-resource-registry/pull/237
changes to the ServiceResource model in resource-registry which has resulted in the bug:
https://github.com/Altinn/altinn-access-management/issues/504

where delegation of MaskinportenSchema is now broken in TT02 and all AT environments.

### Tasks

- [x] Copy new models from resource-registry (since no package is yet available)
- [x] Update breaking model changes in code (e.g. PolicyInformationPoint.GetRights which checks for IsComplete)
- [x] Fix any breaking tests
