### ISSUE TITLE
Rights Received API endpoint (GET /{party}/rights/delegation/received)

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#501]
### Description

Swagger hub API design of the endpoint: https://app.swaggerhub.com/apis/jonkjetiloye/Accessmanagement/1.0.0#/Rights%20delegation/GetRightDelegationReceived

We need a new Rights API endpoint for GET requests for retrieving all Received single rights delegations for a given reportee party.

All received single rights performed in the [POST endpoint](https://github.com/Altinn/altinn-access-management/issues/472) for resources from the resource-registry or A3 Altinn apps, To the reportee party should be returned by this new endpoint. 

Being clarified:
- [ ] Should SSN for persons be sensored or not?

### Tasks

- [ ] New GET endpoint in the Rights controller requiring Read for the 'altinn_access_management' system resource for the reportee {party}
- [ ] Right service implementation which based on the reportee {party} looks up both all received resources and delegated apps

### Acceptance Criterias

As a main administrator/tilgangsstyrer or user with Read access for the altinn_access_management resource (w/ security level 3 requirement), for a reportee/myself
I should be authorized to retrieve received rights for the reportee/myself
for all resource-registry resources or altinn 3 app the reportee/myself have received from others
including detailes about the action/rights and the delegating org/person/user

### Dependencies
-  blocked by this #472
