### ISSUE TITLE
Update models for RightDelegationCheckResult and RightsDelegationResult

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#526]
### Description

Response models for the APIs:
POST RightsController.DelegationCheck
POST MaskinportenSchemaController.Offered

are not in sync with intended API design:
Rights DelegationCheck: https://app.swaggerhub.com/apis/jonkjetiloye/Accessmanagement/1.0.0#/Rights%20delegation/PostRightsDelegationDelegationCheck
MaskinportenSchema Delegation (and later to be reused for Rights Delegation):
https://app.swaggerhub.com/apis/jonkjetiloye/Accessmanagement/1.0.0#/MaskinportenSchema%20delegation/post__party__maskinportenschema_offered

### Tasks

- [ ] Update models
- [ ] Update controllers and mapping
- [ ] Update service implementation for setting DelegationStatus response for API delegation
- [ ] Update integration tests
