### ISSUE TITLE
API-delegering | S1a 

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management#56]
Develop view in picture below. See updated view in figma: https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=1209%3A8163

Frontend tasks on hold:

- [ ] Add icon prop in "Deleger nytt API"-button | waiting for https://github.com/Altinn/altinn-design-system/issues/103
- [ ] Populate Accordions with data | Waiting for mock backend endpoint #67 
- [ ] Make sure buttons sends user to right places | waiting for https://github.com/Altinn/altinn-design-system/issues/103
- [ ] Combine all individual components together to create S1a | waiting for https://github.com/Altinn/altinn-design-system/issues/103

Backend tasks:
- [ ] Create backend endpoint for getting delegated APIs info #67
- [ ] Create backend api call that returns an organisations' Received API connections. https://github.com/Altinn/altinn-access-management/issues/55
Documentation: https://docs.altinn.studio/technology/architecture/components/application/solution/altinn-platform/authorization/resourceregistry/

![image](https://user-images.githubusercontent.com/31471142/191730840-0b45798c-a450-4e54-974b-1b20372b3ab0.png)
