### ISSUE TITLE
Move all right delegation API endpoints for Q1 to internal controller

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#614]
### Description

As the MVP for new single right delegation solution won't include API for external system integrations we need to separate the MVP endpoints for integration from existing Altinn 2 UI.
As we need to be able to make any changes needed for the external endpoints without breaking the Q1/MVP solution.

### Tasks

Move rights controller endpoints to a new internal rights controller for all Q1 endpoints:
- [x] POST {party}/rights/delegation/delegationcheck => POST internal/{party}/rights/delegation/delegationcheck
- [x] POST {party}/rights/delegation/offered => POST internal/{party}/rights/delegation/offered
- [x] GET {party}/rights/delegation/offered => GET internal/{party}/rights/delegation/offered
- [x] POST {party}/rights/delegation/offered/revoke => POST internal/{party}/rights/delegation/offered/revoke
- [x] GET {party}/rights/delegation/received => GET internal/{party}/rights/delegation/received
- [x] POST {party}/rights/delegation/received/revoke => POST internal/{party}/rights/delegation/received/revoke
