### ISSUE TITLE
Get AuthorizedParty

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#618]
### Description

BFF will need an updated version of the current API:
`GET lookup/reportee/{partyId}`

In order to support lookup of a valid authorized party based on just having a single access through right delegation for the party.

New API should be implemented under the new AuthorizedParty naming:
`GET /authorizedparty/{partyId}`

### Tasks

- [ ] Move endpoint to AuthorizedPartyController
- [ ] Move service implementation to AuthorizedPartyService and use new AuthorizedPartyList implementation
- [ ] New controller endpoint will need to support both old and new route until frontend is updated
