### ISSUE TITLE
OpenTelemetry for integrations and persistance

### ISSUE THREAD

**Issue by andreasisnes** [Altinn/altinn-access-management#643]
# Description:
Currently, the Access Management API in C# utilizes ILogger for logging functionality. Log messages are written to Application Insights, which then stores them in a Log Analytics Workspace. However, the current usage of ILogger is deemed suboptimal and is resulting in poor quality log messages.

To address this issue, we remove the dependency on ILogger and adopting a more optimal logging approach using OpenTelemetry for enhanced tracing and observability.
```[tasklist]
### Tasks
- [x] Altinn.AccessManagement.Integration
- [x] Altinn.AccessManagement.Persistence
- [x] Altinn.AccessManagement.Core
```
