### ISSUE TITLE
App Configuration - Cleanup

### ISSUE THREAD

**Issue by Thuen** [Altinn/altinn-access-management#657]
# Description
Currently, the Access Management project(s) are using multiple sources of configuration, some of which are not directly under our control. This results in confusion when modifying configurations and poses difficulties in expanding the existing setup.

To resolve this and pave the way for new possibilities, we should migrate all our configurations to the Azure App Config service.

## Tasks
- [ ] Research Azure App Configuration
- [ ] Get overview of current configurations
- [ ] Migrate to new solution
