### ISSUE TITLE
Instansdelegering | Man kan slette en instansdelegering gjort fra innboks/arbeidsflate

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-access-management#666]
## Hva skal lages?
3.0-API for sletting av instansdelegeringer som er gjort eller mottatt. Det skal også lages GUI for å slette instansdelegeringer man har gitt eller mottatt.

## Definisjoner

```[tasklist]
### Avklaringer
- [ ] Skal brukerstyrte instansdelegeringer fra Apps også kunne slettes fra GUI? Hvis nei, vil det medføre en del ekstra arbeid for autorisasjon.
```

## Akseptansekriterier
Gitt at en bruker har mottatt instansdelegering fra andre, skal bruker selv kunne slette mottatt delegering fra brukerflaten.

Gitt at en bruker har gitt tilgang til en gitt instans til andre, da skal bruker kunne slette/trekke tilbake delegeringen fra brukerflaten.

Gitt at det er gjort en instansdelegering på et element i innboksen
Og instansen senere er blitt slettet fra innboksen
Da skal det fortsattt være mulig å slette fullmakten for både mottaker og den som har utført delegeringen

### Tasks UX
- [ ] Lag skisse for sletting av mottatte instansdelegeringer
- [ ] Lag skisse for sletting av gitte instansdelegeringer

### Tasks Frontend
- [ ] Add a draft title or issue reference here

### Tasks Backend
- [ ] https://github.com/Altinn/altinn-access-management/issues/845
- [ ] https://github.com/Altinn/altinn-access-management/issues/843
- [ ] Implementer API GET delegation/received (for å se mottatte delegeringer)
- [ ] Implementer API POST delegation/received/revoke (så mottakeren kan slette delegeringer)
- [ ] Implementer stored procedures i databasen????????

### Tasks Test
- [ ] Skriv bruno-tester
- [ ] Skriv cypress-tester
- [ ] Finn testbrukere for bruno og cypress tester (i hvert miljø hvis det trengs)

## Avklaringer
1. Skal sletting av instansen fra innboksen utløse "automatisk" sletting av instansdelegeringer som er gjort på instansen

**Comment by ivartryti** [comment]
Forslag til bruno-tester:
- Delegering fra person til person
- Mottakende person kan slette delegering
- Personen som ga tilgang kan trekke tilbake delegeringen 
- 
- Delegering fra person til organisasjon
- Mottakende organisasjon kan slette delegering
- Personen som ga tilgang kan trekke tilbake delegeringen 

- Delegering fra organisasjon til person
- Mottakende person kan slette delegering
- Organisasjonen som ga tilgang kan trekke tilbake delegeringen 

- Delegering fra organisasjon til organisasjon
- Mottakende organisasjon kan slette delegering
- Organisasjonen som ga tilgang kan trekke tilbake delegeringen
