### ISSUE TITLE
Support migration of lenkeservices including delegations

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#678]
### Description

We need to todo

### In scope

The following steps are required to migrate a link service to Altinn 3 Resource  Registry

- [ ] Possible to import resource with policy
- [ ] Posible to disable Altinn 2 service delegations/deletation
- [ ] Possible to migrate the delegations to Altinn 3 Access Management
- [ ] Possible to authorize request for a new

**Comment by TheTechArch** [comment]
duplicate
