### ISSUE TITLE
DelegatableResourceAPI

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#69]
### Description

Access management needs to provide information about the available delegatable resources

## Consideration

From the front end, it should be possible to give input on what type of resources should be listed. 
- APISchema
- Altinn 2 Service
- Altinn 3 App
- Generic resources?
- +++

### Authorization

Resources the user is not authorized to delegate should not be visible as a search result.

For resource/app policies, we need to create an algorithm that can quickly check against the user's list of roles/access groups without needing to parse XACML policy each time. 

### Additional Information

This API would probably also be used by external clients. Need to have a good API description

### Tasks
 - [ ] Create DelegateableResource API
 - [ ] Define models used by app

### Acceptance Criteria

- [ ] Can list resources of a specific type (API scheme, apps)
- [ ] List only resources that the user is authorized to delegate
- [ ] API requires authentication
