### ISSUE TITLE
Rotate JWK for OedAuthzMaskinportenClient

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#722]
### Description

The JWKs for the client needs to be rotated before 05.07.2024 for all environments for both AT/TT and Prod.

### Additional Information

Link to slack alert:
https://altinndevops.slack.com/archives/C014H7WPSUB/p1715851075108729

Link to docs:
https://docs.altinn.studio/technology/solutions/cli/configuration/maskinporten-setup

Link to Samarbeidsportalen (@digdir login):
https://sjolvbetjening.test.samarbeid.digdir.no/integrations

### Tasks

- [x] Create new JWK for Test
- [x] Create new JWK for Prod
- [x] Add JWK for Test to Test client in Samarbeidsportalen
- [x] Add JWK for Prod to Prod client in Samarbeidsportalen (needs Ragnhild or someone else with access for this step)
- [x] Update Secret in Platform KV for all Test environments with new expiry (can ask platform team for assistance)
- [x] Update Secret in Platform KV for Prod environments with new expiry (can ask platform team for assistance)

### Acceptance Criterias

JWK is rotated in time so OED Apps don't experience downtime
