### ISSUE TITLE
Etablere nye tilgangspakker

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management#725]
### Description
Lage datamodell for tilgangspakker
Metadata 
API for administrasjon for tilgangspakkene (nye pakker, endre ER-knytninger, navn beskrivelse osv)
Tags/nøkkelord?

### Additional Information
https://docs.altinn.studio/authorization/what-do-you-get/accessgroups/type-accessgroups/versjon-3/

```[tasklist]
### Tasks
- [x] Oppdater dokumentasjon om fullmakts-/tilgangsgrupper
- [ ] https://github.com/Altinn/altinn-access-groups/issues/14
- [ ] https://github.com/Altinn/altinn-access-groups/issues/12
- [ ] https://github.com/Altinn/altinn-access-groups/issues/13
```

### Avhengigheter
Er-kopi må være ferdig før denne løsningen kan tas i bruk.

**Comment by rtafj** [comment]
Se https://github.com/Altinn/altinn-authorization-tmp/issues/47
