### ISSUE TITLE
Tilgangsliste autorisasjon ved delegering av enkelttjenester

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#752]
```[tasklist]
### Tasks
- [x] Ny klient for integrasjon med authorization/api/v1/accesslist/accessmanagement/authorization
- [x] Oppdatere SingleRightsService.RightsDelegationCheck for tilgangsliste autorisasjon
- [x] Oppdatere SingleRightsService.RightsDelegation for evt. tilgangsliste autorisasjon
- [x] Integrasjonstester
- [x] Automatiserte Brunotester
```

**Comment by howieandersen** [comment]
@sneha-sirure @jonkjetiloye 

Er denne klar til å bli closed?

**Comment by sneha-sirure** [comment]
@howieandersen @jonkjetiloye Ja, den er testet ok skal lukke tasken.
