### ISSUE TITLE
API-delegering finish flow

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management#77]
### Tasks

- [ ] Fix routing for all 'Forrige' and 'Neste'-buttons.
- [ ] Set background color on all Pages.
- [ ] Set spacing and width on all Pages
- [ ] Make x-button and fix routing on it.
- [ ] #216
- [ ] Make "deleger nytt API"-button in overview take you directly to api-delegations/new-api page with redux state newOrgDelegations prefilled
- [ ] Flush redux states when returning to /api-delegations
- [ ] Add around 70 px to margin-bottom for navButtonContainers

See sketches: https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=1209%3A8163&t=c5Lh5Vd6OpNXUx8Q-0

AC: 
- [ ] Every button does results in expected behaviour
