### ISSUE TITLE
Get all the delegated resources by the reportee (outbound delegations)

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management#79]
### Description

Get all the delegated resources (api) by the reportee to others. The new userinterface [here](https://www.figma.com/proto/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=4352%3A114741&scaling=min-zoom&page-id=1209%3A8163&starting-point-node-id=4352%3A114741) requires that the api returns the following details to the frontend

- resource(api) title
    - Name of the organisation the resource was delegated to

### Tasks

- [x] Create an endpoint to list all the delegated resources
- [x] Add integration with sblbridge to get the party information 
- [x] Test with different input
- [x] Create unit tests for the new endpoint

### Acceptance Criterias
- [ ] The endpoint is accessible at accessmanagement/api/v1/{who}/delegations/maskinportenschema/outbound
- [ ] The endpoint must return a list of delegations with resource information

_No response_

**Comment by acn-dgopa** [comment]
https://github.com/Altinn/altinn-authorization/issues/65

**Comment by acn-dgopa** [comment]
Available for testing after deploy to the test environment
