### ISSUE TITLE
bruno tester for GetMaskinportenDelegations (Issues #175, #299, #326, #377)

### ISSUE THREAD

**Issue by ivartryti** [Altinn/altinn-access-management#824]
### Description

I dag er det bare én happy flow automatisert bruno test for GetMaskinportenDelegations (Issues #175, #299, #326, #377). Lag brunotester for resten av akseptansekriteriene også.
Se også #641 for en oversikt over issues der vi må sjekke testdekning.

Må lage tester med:
- [ ] gylding supplierOrg og consumerOrg med delegeringer
- [ ] gylding supplierOrg og consumerOrg uten delegeringer
- [ ] ugyldig supplierOrg
- [ ] ugyldig consumerOrg?
- [ ] ugylding supplierOrg og consumerOrg?
- [ ] ugyldig scope

### Tasks

- [ ] Receive the same HTTP status, message and body responses as before, for successful lookups when delegations exist
- [ ] Receive the same HTTP status, message and body responses as before, for successful lookups when no delegations exist
- [ ] Receive the same HTTP status, message and body responses as before, for errors/failure situations
- [ ] Token Authorization Scope; "altinn:maskinporten/delegations", should only give access to lookup delegations for the service owners own resources
- [ ] Token Authorization Scope; "altinn:maskinporten/delegations.admin", should give access to lookup delegations for any maskinporten scope delegation
- [ ] Without a valid token with authorized scope should give same error as in A2
