### ISSUE TITLE
Instansdelegering | L2 Instansdelegeringer i ny brukerflate

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#826]
# Beskrivelse
L1 av instansdelegering fokuserer på behovene for brukerstyrt instansdelegering fra Apps, og har da laget grunnlaget for støtte for instansdelegering i autorisasjonsløsnigen i Altinn 3.

I denne leveransen bygger man videre for å legge til rette for instansdelegering fra ny meldingsboks/dialogporten og gjennom sluttbruker API integrasjoner for at brukere og organisasjoner kan dele tilgang til enkelt elementer i sin meldingsboks med andre som skal ha tilgang til hele eller deler av instansen.

Denne epic'en vil involvere:
- Nytt brukergrensesnitt for opprettelse av instansdelegering som kan dyplenkes til fra meldingsboks/eksterne
- Nytt brukergrensesnitt for å se og trekke gitte instanstilganger
- Nytt brukergrensesnitt for å se og si fra seg mottatte instanstilganger

## Definisjoner
`Instans` - et eksemplar av en app/ressurs/tjeneste
`Instans ID` - identifikator for en gitt instans av en app/ressurs/tjeneste
`Instans-eier` - part som er eier av en gitt instans av en app/ressurs/tjeneste. Kan være både en bruker eller en organisasjon.
`Applikasjonsflyt` - del av prosessen å fylle ut eller utføre handlinger i en app instans. Typisk: fylle ut skjema, signere og sende inn skjema.

# Avklaringer
- [ ] Skal vi tilby å instansdelegere enkeltelementer i en etablert dialog?
- [ ] Skal det være mulig å sperre en ressurs for instansdelegering? Spørsmål fra Skatt om vi har vurdert å lage mulighet for å sette begrensning på ressursdefinisjonen på mulighet for instansdelegering, og om det er hensiktsmessig.

### Features
- [ ] https://github.com/Altinn/altinn-access-management/issues/665
- [ ] https://github.com/Altinn/altinn-access-management/issues/666
- [ ] https://github.com/Altinn/altinn-access-management/issues/667
- [ ] https://github.com/Altinn/altinn-access-management/issues/668
- [ ] https://github.com/Altinn/altinn-access-management/issues/669
- [ ] https://github.com/Altinn/altinn-access-management/issues/670

```[tasklist]
### Test Plan
- [ ] ToDo
```
