### ISSUE TITLE
Evaluating ownership

### ISSUE THREAD

**Issue by sorensensig** [Altinn/altinn-access-management#83]
### Description

This _chore_ looks to clarify questions regarding ownership, whether it changes due to the concept, and if so, how.

This _chore_ is part of Epic #82 

### Tasks

- [ ] **Should Authorization own extensions?** `(Admin)`
E.g., Tag editor, NACE descriptions and Quality Assurance

> Prerequisite:
> - [ ] Not defined

> Next steps:
> - [ ] In a team meeting, if any, create a list of prerequisites for this tasks to continue.
> - [ ] In a team meeting, fill out considerations as next steps tasks.

> Clarifications:
> Not defined

---
- [ ] **Who acts as a data controller ("behandlingsansvarlig")?** `(Legal)`
Who is responsible for processing what in the relationship between service owners, businesses and Altinn when it comes to acting on behalf of the business.

> Prerequisite:
> - [ ] Not defined

> Next steps:
> - [ ] In a team meeting, if any, create a list of prerequisites for this tasks to continue.
> - [ ] In a team meeting, fill out considerations as next steps tasks.

> Clarifications:
> Not defined

> Notes:
> Service owners should be responsible when users use their services. We do not wish to take over the responsibility of being the data controller.

---
- [ ] **Who should own and maintain the taxonomy?** `(Admin)`

> Prerequisite:
> - [ ] Not defined

> Next steps:
> - [ ] In a team meeting, if any, create a list of prerequisites for this tasks to continue.
> - [ ] In a team meeting, fill out considerations as next steps tasks.

> Clarifications:
> Not defined
