### ISSUE TITLE
DAST testing med Polaris fAST Dynamic

### ISSUE THREAD

**Issue by howieandersen** [Altinn/altinn-access-management#860]
### Description

Team Tilgangsstyring og Kontroll skal begynne å utforske Dynamic Application Security Testing (DAST), med bistand fra BOD sin sikkerhetsfaggruppe.

### Additional Information

Til dette formålet har faggruppen valgt sikkerhetsplatformen Polaris som grunnlag, og vi skal dermed ta i bruk [Polaris fAST Dynamic](https://www.blackduck.com/blog/fast-dynamic-dast.html) som verktøy.

### Tasks

- [x] Velge hvilke DAST metoder som skal tas i bruk
- [x] Velge endepunkter som skal testes i første omgang
- [x] Konfigurere bruk av tokens
- [x] Gjennomføre testing av valgte endepunkter

### Acceptance Criterias

Vi har satt opp en fungerende PoC på hvordan man kjører DAST på AccessManagement API ved bruk av Polaris fAST Dynamic, som er klar til å skalere ut til andre endepunkter og eventuelt automatiseres som del av build+test CICD pipeline.
