### ISSUE TITLE
Backend: Rename of projects and namespaces from AuthorizationAdmin to AccessManagement

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#91]
### Description

All projects. folders and namespaces in the backend solution in the repository should be renamed to match the name of the repository:

Altinn.AuthorizationAdmin -> Altinn.AccessManagement

### Tasks

- [x] Rename projects
- [x] Update project references in solution file
- [x] Rename all namespaces
- [x] Fix casing API
- [x] Remove frontend code and config
- [x] Fix folder structure
- [x] Update Docker file
