### ISSUE TITLE
Table with overview over resources connected to groups/roles

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#92]
### Description

There are several scenarios where we need to know which resource is connected to a role/group without needing to parse every XACML policy.

The suggestion is to create a new table in authorization where we store all/some subject information for a policy

Table PolicySubjects 

- Altinn roles
- Altinn groups
- external roles and groups

### Additional Information

It should be possible to quickly identify which resources a specific role/group gives access to

What about local groups/roles? 

### Tasks

- [ ] Define table structure
- [ ] Update policy store to always update/add this information when the policy is migrated

### Acceptance Criteria
- [ ] Table is updated when app policy is updated
- [ ] Table is updated when resource policy is updated
- [ ]
