### ISSUE TITLE
We need an API that based on resource can list rights for an resource

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#94]
### Description

When a user wants to delegate rights for a resource, we need an API that can list all rights that the user can delegate. (eg actions for the specific resources)

This will be used both for presenting what can be delegated and also to verify when delegating the rights that is allowed to be delegated.

### Additional Information

The response object should probably be a list of rights

```json
[{
"SubjectMatch": {
"altinn.role":"DAGL"
},
"resource": {
"altinn.app.org": "skd",
"altinn.app.app":"flyttemelding",
"altinn.task":"Task1"
},
"Action" : ["Read", "Write"]
},
{
"SubjectMatch": {
"altinn.role":"DAGL"
},
"resource":{
"altinn.app.org": "skd",
"altinn.app.app":"flyttemelding",
"altinn.task":"Task2"
},
"Action" : ["Sign"]
}
]

```

The changes should probably be added to the ABAC module for reuse. 

The input could be an enriched XACML request with all claims needed to evaluate every rule in an XACML Policy

### Should we list why we have access?

One option is to return all rules with subject info that matches. In this way, it is possible to present to the user 

### Tasks

- [ ] Define XACMLRight model in ABAC 
- [ ] Identify code reuse from delegation scenario? 
- [ ] Build matching code
- [ ] Build API that includes delegated rights for a resource 

### Acceptance Criteria
- [ ] The API is able to list all rights for a specific resource
- [ ] Includes delegated rights
- [ ] Includes all resources defined in the policy
- [ ] Includes all actions defined in the policy
- [ ] Shows which right that is delegatable
